async_command_bus:
  connections:
    default:
      host: 'localhost'
      port: 5672
      user: 'guest'
      password: 'guest'
    second:
      host: 'localhost'
      port: 5672
      user: 'guest'
      password: 'guest'
      vhost: 'test_vhost'
  exchanges:
    test_exchange_name:
      connection: second
      name: test_exchange
      type: direct
    delayed_exchange:
      connection: default
      name: delayed_exchange
      type: direct
      delayed_active: true
  queues:
    first_queue_name:
      connection: default
      name: first_queue
    second_queue_name:
      connection: second
      name: second_queue
      passive: false
      durable: false
      exclusive: false
      auto_delete: false
  bindings:
    test_binding:
      queue: second_queue_name
      exchange: test_exchange_name
      routing_key: test_routing_key
    delayed_exchange_binding:
      queue: first_queue_name
      exchange: delayed_exchange
      routing_key: another_simple_command
  commands:
    command_published_to_delayed_exchange:
      class: App\Command\AnotherSimpleCommand
      publisher:
        exchange:
          name: delayed_exchange
          routing_key: another_simple_command
    command_published_to_exchange:
      class: App\Command\DispatchedToOwnQueueCommand
      publisher:
        exchange:
          name: test_exchange_name
          routing_key: test_routing_key
