services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Siemieniec\AmqpMessageBus\:
        resource: '../src/'

    Siemieniec\AmqpMessageBus\Config\ConfigFactory: ~

    Siemieniec\AmqpMessageBus\Config\Config:
        factory: ['@Siemieniec\AmqpMessageBus\Config\ConfigFactory', 'create']
        arguments: ['%amqp_message_bus%']
